### ISSUE TITLE
Add #![no_std] to allow no_std codebase to use your library

### ISSUE THREAD

**Issue by KSXGitHub** [myrrlyn/wyz#1]
Your library seems to not depend on `std`, it would be a waste if no_std codebase cannot use this.

**Comment by myrrlyn** [comment]
```toml
# Cargo.toml

[dependencies.wyz]
default-features = false
```

[It is `#![no_std]`](https://github.com/myrrlyn/wyz/blob/master/src/lib.rs#L10), but since it comes with some parts that do use `std`, you have to turn those off.

I am considering making each module its own feature-gate, which would *still* require turning off `default-features`, but I haven't yet had a need to skip compilation of any of them.
